version: '3.8'
services:
  web:
    build: .
    develop:
      watch:
        - action: rebuild
          path: ./
    ports:
      - "80:80"
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:latest
    networks:
      - app-network

networks:
  app-network:
    driver: bridge